# Generated by Django 5.1.6 on 2025-03-24 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuss",
            name="slide_image1",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="slide_image2",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="slide_image3",
        ),
        migrations.AddField(
            model_name="aboutuss",
            name="slide_images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
