# Generated by Django 5.1.6 on 2025-03-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0002_remove_aboutuss_slide_image1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuss",
            name="slide_images",
        ),
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slide_images/")),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_images",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
    ]
