# Generated by Django 5.1.6 on 2025-03-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0003_remove_aboutuss_slide_images_slideimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission_vision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "our_mission",
                    models.CharField(
                        default="Default mission statement", max_length=255
                    ),
                ),
                (
                    "our_vision",
                    models.CharField(
                        default="Default vision statement", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="our_mission",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="our_vision",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_description1",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_description2",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_description3",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_description4",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_title1",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_title2",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_title3",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="values_title4",
        ),
        migrations.RemoveField(
            model_name="aboutuss",
            name="we_values",
        ),
        migrations.RemoveField(
            model_name="slideimage",
            name="about_uss",
        ),
        migrations.AlterField(
            model_name="slideimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="slide_images/"),
        ),
        migrations.CreateModel(
            name="ExecutiveTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_team",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
    ]
