# Generated by Django 5.1.6 on 2025-03-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0004_mission_vision_value_remove_aboutuss_our_mission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveteam",
            name="about_uss",
        ),
        migrations.DeleteModel(
            name="Mission_vision",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
        migrations.DeleteModel(
            name="aboutUss",
        ),
        migrations.DeleteModel(
            name="ExecutiveTeam",
        ),
    ]
