# Generated by Django 5.1.6 on 2025-03-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveteam",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="slideimage",
            name="about_uss",
        ),
        migrations.DeleteModel(
            name="MissionVision",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
        migrations.DeleteModel(
            name="ExecutiveTeam",
        ),
        migrations.DeleteModel(
            name="aboutUss",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
    ]
