# Generated by Django 5.1.6 on 2025-03-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0008_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="value",
            name="value_description",
        ),
        migrations.AlterField(
            model_name="missionvision",
            name="about_uss",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="aboutUss.aboutuss",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="description",
            field=models.CharField(default="Default description", max_length=255),
        ),
        migrations.AlterField(
            model_name="value",
            name="title",
            field=models.CharField(default="Default title", max_length=50),
        ),
    ]
