# Generated by Django 5.1.6 on 2025-03-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0009_remove_value_value_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveteam",
            name="name",
        ),
        migrations.RemoveField(
            model_name="executiveteam",
            name="position",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="our_mission",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="our_vision",
        ),
        migrations.RemoveField(
            model_name="value",
            name="description",
        ),
        migrations.RemoveField(
            model_name="value",
            name="title",
        ),
        migrations.AlterField(
            model_name="missionvision",
            name="about_uss",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission",
                to="aboutUss.aboutuss",
            ),
        ),
    ]
