# Generated by Django 5.1.6 on 2025-03-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0010_remove_executiveteam_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="value",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="executiveteam",
            name="about_uss",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
        migrations.DeleteModel(
            name="MissionVision",
        ),
        migrations.DeleteModel(
            name="aboutUss",
        ),
        migrations.DeleteModel(
            name="ExecutiveTeam",
        ),
    ]
