# Generated by Django 5.1.6 on 2025-03-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aboutUss", "0011_remove_value_about_uss_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="aboutUss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_description",
                    models.CharField(
                        default="Default description statement", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutiveTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_team",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "our_mission",
                    models.CharField(
                        default="Default mission statement", max_length=255
                    ),
                ),
                (
                    "our_vision",
                    models.CharField(
                        default="Default vision statement", max_length=255
                    ),
                ),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slide_images/")),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_images",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "about_uss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="aboutUss.aboutuss",
                    ),
                ),
            ],
        ),
    ]
