# Generated by Django 5.1.6 on 2025-04-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0012_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="value",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="executiveteam",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="about_uss",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
        migrations.DeleteModel(
            name="ExecutiveTeam",
        ),
        migrations.DeleteModel(
            name="aboutUss",
        ),
        migrations.DeleteModel(
            name="MissionVision",
        ),
    ]
