# Generated by Django 5.1.6 on 2025-04-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUss", "0014_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveteam",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="missionvision",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="value",
            name="about_uss",
        ),
        migrations.RemoveField(
            model_name="value",
            name="description",
        ),
        migrations.RemoveField(
            model_name="value",
            name="title",
        ),
        migrations.CreateModel(
            name="ValueDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "Value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_details",
                        to="aboutUss.value",
                    ),
                ),
            ],
        ),
    ]
