# Generated by Django 5.1.6 on 2025-04-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0002_alter_hero_tab_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="tab_description",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="tab_image",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="tab_title",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="hero",
            name="hero_description",
            field=models.CharField(
                default="Default description statement", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="hero_title",
            field=models.CharField(
                default="Default description statement", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=255)),
                ("customer_images", models.ImageField(upload_to="customer_image/")),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                    ),
                ),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(default="question question", max_length=255),
                ),
                ("answer", models.CharField(default="Default answer", max_length=255)),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OurService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ourservice_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                ("service_logo", models.ImageField(upload_to="service_logo/")),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_logos",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_image", models.ImageField(upload_to="slide_images/")),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_images",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlideLogos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_logo", models.ImageField(upload_to="slide_logos/")),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_logos",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StableLogos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stable_logo", models.ImageField(upload_to="stable_logos/")),
                (
                    "sort_title",
                    models.CharField(default="Default statement", max_length=10),
                ),
                (
                    "sort_description",
                    models.CharField(default="Default statement", max_length=10),
                ),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stable_logos",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                ("work_logo", models.ImageField(upload_to="work_description/")),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "hero_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_description",
                        to="hero.hero",
                    ),
                ),
            ],
        ),
    ]
