# Generated by Django 5.1.6 on 2025-04-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0003_remove_hero_cover_image_remove_hero_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerreview",
            name="hero_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_reviews",
                to="hero.hero",
            ),
        ),
        migrations.AlterField(
            model_name="customerreview",
            name="name",
            field=models.CharField(default="customer_reviews", max_length=255),
        ),
    ]
