# Generated by Django 5.1.6 on 2025-04-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0004_alter_customerreview_hero_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="workdescription",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="stablelogos",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="slideimage",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="slidelogos",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="ourservice",
            name="hero_title",
        ),
        migrations.DeleteModel(
            name="CustomerReview",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.DeleteModel(
            name="WorkDescription",
        ),
        migrations.DeleteModel(
            name="StableLogos",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
        migrations.DeleteModel(
            name="SlideLogos",
        ),
        migrations.DeleteModel(
            name="hero",
        ),
        migrations.DeleteModel(
            name="OurService",
        ),
    ]
