# Generated by Django 5.1.6 on 2025-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="customer_images/")),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="customerreview",
            name="customer_images",
        ),
        migrations.AddField(
            model_name="customerreview",
            name="customer_images",
            field=models.ManyToManyField(to="hero.customerimage"),
        ),
    ]
