# Generated by Django 5.1.6 on 2025-04-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0007_customerimage_remove_customerreview_customer_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerreview",
            name="customer_images",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.DeleteModel(
            name="hero",
        ),
        migrations.DeleteModel(
            name="Logos",
        ),
        migrations.DeleteModel(
            name="OurService",
        ),
        migrations.DeleteModel(
            name="WorkDescription",
        ),
        migrations.DeleteModel(
            name="CustomerImage",
        ),
        migrations.DeleteModel(
            name="CustomerReview",
        ),
    ]
