# Generated by Django 5.1.6 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0009_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slide_images/")),
                (
                    "description",
                    models.CharField(default="Default description", max_length=255),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hero",
            name="slide_image",
        ),
        migrations.AddField(
            model_name="hero",
            name="slide_images",
            field=models.ManyToManyField(related_name="heroes", to="hero.slideimage"),
        ),
    ]
