# Generated by Django 5.1.6 on 2025-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0010_slideimage_remove_hero_slide_image_hero_slide_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideimage",
            name="description",
        ),
        migrations.AlterField(
            model_name="hero",
            name="slide_images",
            field=models.ManyToManyField(related_name="hero", to="hero.slideimage"),
        ),
    ]
