# Generated by Django 5.1.6 on 2025-04-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0011_remove_slideimage_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerReview",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="slide_images",
        ),
        migrations.DeleteModel(
            name="Logos",
        ),
        migrations.DeleteModel(
            name="OurService",
        ),
        migrations.DeleteModel(
            name="WorkDescription",
        ),
        migrations.DeleteModel(
            name="hero",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
    ]
