# Generated by Django 5.1.6 on 2025-04-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0013_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logos",
            name="slide_logo",
        ),
        migrations.CreateModel(
            name="SlideLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_logo", models.ImageField(upload_to="slide_logos/")),
                (
                    "logos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_logos",
                        to="hero.logos",
                    ),
                ),
            ],
        ),
    ]
