# Generated by Django 5.1.6 on 2025-04-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0014_remove_logos_slide_logo_slidelogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slidelogo",
            name="logos",
        ),
    ]
