# Generated by Django 5.1.6 on 2025-04-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0015_remove_slidelogo_logos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ourservice",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ourservice",
            name="service_logo",
        ),
        migrations.RemoveField(
            model_name="ourservice",
            name="title",
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_logo", models.ImageField(upload_to="service_logo/")),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "service_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="hero.ourservice",
                    ),
                ),
            ],
        ),
    ]
