# Generated by Django 5.1.6 on 2025-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0017_inquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
