# Generated by Django 5.1.6 on 2025-04-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0018_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
