# Generated by Django 5.1.6 on 2025-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0019_subscribe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="cover_image",
        ),
    ]
