# Generated by Django 5.1.6 on 2025-04-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0020_remove_hero_cover_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerReview",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.RemoveField(
            model_name="slideimage",
            name="hero",
        ),
        migrations.DeleteModel(
            name="Inquiry",
        ),
        migrations.DeleteModel(
            name="Logos",
        ),
        migrations.DeleteModel(
            name="Office",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_detail",
        ),
        migrations.DeleteModel(
            name="SlideLogo",
        ),
        migrations.DeleteModel(
            name="Subscribe",
        ),
        migrations.DeleteModel(
            name="WorkDescription",
        ),
        migrations.DeleteModel(
            name="hero",
        ),
        migrations.DeleteModel(
            name="SlideImage",
        ),
        migrations.DeleteModel(
            name="OurService",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
