# Generated by Django 5.1.6 on 2025-04-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hero", "0021_delete_customerreview_delete_faq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="customer_reviews", max_length=255)),
                ("customer_images", models.ImageField(upload_to="customer_image/")),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(default="question question", max_length=255),
                ),
                ("answer", models.CharField(default="Default answer", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Default description statement", max_length=255
                    ),
                ),
                (
                    "hero_description",
                    models.CharField(
                        default="Default description statement", max_length=255
                    ),
                ),
                ("image", models.ImageField(upload_to="slide_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Logos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stable_logo", models.ImageField(upload_to="stable_logos/")),
                (
                    "sort_title",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "sort_description",
                    models.CharField(default="Default statement", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="OurService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ourservice_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlideLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_logo", models.ImageField(upload_to="slide_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="WorkDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                ("work_logo", models.ImageField(upload_to="work_description/")),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_logo", models.ImageField(upload_to="service_logo/")),
                ("title", models.CharField(default="Default statement", max_length=50)),
                (
                    "description",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "service_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="hero.ourservice",
                    ),
                ),
            ],
        ),
    ]
