# Generated by Django 5.1.6 on 2025-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0022_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="button_link",
            field=models.CharField(default="http//###########", max_length=255),
        ),
    ]
