# Generated by Django 5.1.6 on 2025-03-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="about_description",
            field=models.CharField(
                default="Default description statement", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="our_mission",
            field=models.CharField(default="Default mission statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="our_vision",
            field=models.CharField(default="Default vision statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="slide_image1",
            field=models.ImageField(blank=True, null=True, upload_to="slide_image1/"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="slide_image2",
            field=models.ImageField(blank=True, null=True, upload_to="slide_image2/"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="slide_image3",
            field=models.ImageField(blank=True, null=True, upload_to="slide_image3/"),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_description1",
            field=models.CharField(default="Default statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_description2",
            field=models.CharField(default="Default statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_description3",
            field=models.CharField(default="Default statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_description4",
            field=models.CharField(default="Default statement", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_title1",
            field=models.CharField(default="Default statement", max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_title2",
            field=models.CharField(default="Default statement", max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_title3",
            field=models.CharField(default="Default statement", max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="values_title4",
            field=models.CharField(default="Default statement", max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="we_values",
            field=models.CharField(default="Default statement", max_length=50),
        ),
    ]
