# Generated by Django 5.1.6 on 2025-03-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUS", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aboutUs",
        ),
    ]
