# Generated by Django 5.1.6 on 2025-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aboutUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_description",
                    models.CharField(
                        default="Default description statement", max_length=255
                    ),
                ),
                (
                    "slide_image1",
                    models.ImageField(blank=True, null=True, upload_to="slide_image1/"),
                ),
                (
                    "slide_image2",
                    models.ImageField(blank=True, null=True, upload_to="slide_image2/"),
                ),
                (
                    "slide_image3",
                    models.ImageField(blank=True, null=True, upload_to="slide_image3/"),
                ),
                (
                    "our_mission",
                    models.CharField(
                        default="Default mission statement", max_length=255
                    ),
                ),
                (
                    "our_vision",
                    models.CharField(
                        default="Default vision statement", max_length=255
                    ),
                ),
                (
                    "we_values",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "values_title1",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "values_description1",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "values_title2",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "values_description2",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "values_title3",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "values_description3",
                    models.CharField(default="Default statement", max_length=255),
                ),
                (
                    "values_title4",
                    models.CharField(default="Default statement", max_length=50),
                ),
                (
                    "values_description4",
                    models.CharField(default="Default statement", max_length=255),
                ),
            ],
        ),
    ]
