# Generated by Django 5.1.6 on 2025-03-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUS", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutus",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="values_description4",
        ),
    ]
