# Generated by Django 5.1.6 on 2025-03-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutUS", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutus",
            old_name="tab_title",
            new_name="values_description4",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="tab_description",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="tab_image",
        ),
    ]
