# Generated by Django 5.1.6 on 2025-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_image",
                    models.ImageField(blank=True, null=True, upload_to="client_image/"),
                ),
                (
                    "logo_image",
                    models.ImageField(blank=True, null=True, upload_to="logo_image/"),
                ),
                ("logo_title", models.CharField(max_length=255)),
                ("logo_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
